- name: Upgrade Mapr Spark (Redhat / CentOS)
  yum:
    name: mapr-spark
    state: latest
  when:
    - ansible_os_family == 'RedHat'

- name: Upgrade History-Server
  shell: "yum -y update {{ item }}"
  with_items:
    - mapr-spark-historyserver
    - mapr-spark-master
  when:
    - ansible_os_family == 'RedHat'
  ignore_errors: yes
