- name: "PIP as Dependency must be installed"
  shell: "yum install -y python-pip"

- name: "Upgrading the MapR Streams Python Client ( Optional )"
  shell: 'pip install -U --global-option=build_ext --global-option="--library-dirs=/opt/mapr/lib" --global-option="--include-dirs=/opt/mapr/include/" {{ mapr_ecosystem_url }}mac/mapr-streams-python-0.9.2.tar.gz'
  ignore_errors: yes
